language: java

jdk: openjdk8

services:
- mysql

before_install:
- mysql -u root --password=  < ./sql/init.sql

script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi


install:
- ./mvnw install -Dmaven.javadoc.skip=true -B -V -Ptravis