language: java

jdk: openjdk8

services:
- mysql

before_install:
- mysql -u root --password=  < ./sql/init.sql

script:
- ./mvnw cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)