language: java

jdk: openjdk8

services:
- mysql

before_install:
- mysql -u root --password=  < ./sql/init.sql

script:
- echo "build successful."


install:
- ./mvnw install -Dmaven.javadoc.skip=true -B -V -Ptravis

after_script:
- cd ./dist
- git init
- git config user.name "${U_NAME}"
- git config user.email "${U_EMAIL}"
- git add .
- git commit -m "Update tools"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}