language: java

jdk: openjdk8

services:
- mysql

before_install:
- mysql -u root --password=  < ./sql/init.sql

install: true

script:
- travis_wait 30 ./mvnw clean install -DskipTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true -P travis

after_success:
- bash <(curl -s https://codecov.io/bash)